syntax = "proto3";

package helios.config;

option go_package = "/config";

message BaseComponent {
  string name = 1;

  oneof node_type {
    Component leaf = 2;
    ComponentGroup branch = 3;
  }
}

message Component {
  string path = 1;
  string tag = 2;
  string id = 3;
  string location = 4;
  string hash = 5;
  string type = 6;
  repeated Volume volumes = 7;
  repeated Port ports = 8;
}

message ComponentGroup {
  repeated BaseComponent children = 1;
}

message ComponentTree {
  BaseComponent root = 1;
  string version = 2;
}

message Port {
  string type = 1;
  string source = 2;
  string target = 3;
  string read_only = 4;
}

message Volume {
  string source = 1;
  string target = 2;
  string mode = 3;
}